import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "../component/header";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        <div className="bg-home bg-no-repeat bg-cover min-h-screen">
          {/* bg-transparent agar mengikuti background parent */}
          <div className="bg-home bg-no-repeat bg-cover w-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
